### DISCUSSION TITLE
Metadata structure

### DISCUSSION THREAD

**Discussion by mhpob** [ocean-tracking-network/latitudes#16] [General]
Shifting conversation regarding metadata structure here from #2.

Goal is to have something that is a balance of human- and machine-readable, with a preference toward humans. @jdpye suggested YAML and @chrisholbrook mentioned a few fields, so here's a draft. Fields I think should be mandatory have asterisks.

Pros:
  - human-readable
  - directly translatable to JSON, and so an API (TIL that YAML is just abstracted JSON and all JSON is valid YAML)

Cons:
  - unclear syntax (I don't even think I got the hyphens/indents right here)

Example structure:

```
file:
  name: **
  attribution: **
    - pi_name:
      pi_contact:
    - poc_name:
      poc_contact:
    - citation:
  format: **
  size: **
  recording: **
    - start:
    - end:
  creation_date: **
  exporting_software: **
    - name:
      version:
  instrument: **
    - type: **
      vendor: **
      firmware_version: **
      code_map: **
      serial_number:
      internal_transmitter_id:
  records: **
    transmitter:
      - A:
           n_detected:
           n_detections:
           sensor:
      - B:
    logging:
      - temperature:
           sampling_rate:
           n_records:
           min:
           max:
           median:
      - tilt:
      - battery:
      - etc...
      - event:
         - offload:
             n_events:
             datetime:
         - release:
             n_events:
             datetime:
```
